import "./globals.css";
import LayoutDef from "@/components/Layout";
import PageTransition from "@/components/PageTransition";
import NavigationProgress from "@/components/NavigationProgress";
import ScrollToTop from "@/components/ScrollToTop";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavigationProgress />
        <LayoutDef>
          <PageTransition>
            {children}
          </PageTransition>
        </LayoutDef>
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}
